### ISSUE TITLE
postinstall is missing

### ISSUE THREAD

**Issue by Rendanic** [base2Services/shelvery-aws-backups#112]
I try to build the container with the following commands from the README.md:

```
docker run --rm -it -v $HOME/.aws:/root/.aws -w /src node:latest bash
git clone https://github.com/base2services/shelvery && cd shelvery
npm install -g serverless
postinstall /usr/local/lib/node_modules/serverless/node_modules/spa
```

I am getting the following error:
```
root@bf223b649314:/src/shelvery# postinstall /usr/local/lib/node_modules/serverless/node_modules/spa
bash: postinstall: command not found
```

What is missing in the documentation?

**Comment by toshke** [comment]
@Rendanic there should be no need to execute `postinstall` on your own, it is part of `npm install` process itself. Also, you may want to use SAM as deployment mechanism, more elegant than serverless IMHO - https://github.com/base2Services/shelvery-aws-backups/blob/develop/deploy-sam-template.sh

**Comment by Rendanic** [comment]
I tried SAM and it worked after some modifications to the script.
The example needs some tweaks to work on my side. I'll create a PR to make it more flexible for other users.
Hopefulle the doc for serverless will be modified, because it doesn't work at the moment.

**Comment by toshke** [comment]
@Rendanic can you point us to exact point that failed with npm. I tried and used doco  with success yesterday, I'm unclear on this line -

```
postinstall /usr/local/lib/node_modules/serverless/
```
as I couldn't find it in the doco

**Comment by Rendanic** [comment]
```
docker run --rm -it -v $HOME/.aws:/root/.aws -w /src node:latest bash
git clone https://github.com/base2services/shelvery && cd shelvery
npm install -g serverless
root@1530a29db151:/src/shelvery# node postinstall
```
I get the following error from 'node postinstall'

> 
> internal/modules/cjs/loader.js:1017
>   throw err;
>   ^
> 
> Error: Cannot find module '/src/shelvery/postinstall'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:884:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }

**Comment by toshke** [comment]
I feel like documentation is bit misleading,  as there is no need to
execute 'node postinstall' it was just rendered as sample output and
embedded in README - after 'npm install' , next command should be 'sls
deploy'

**Comment by Rendanic** [comment]
Thanks for the fast reply.
That was my first serverless deployment and I tried it from the documentation.
Hint: Change the commands in **command** or _command_

**Comment by toshke** [comment]
Yeah, was replying from my phone via email,  otherwise I would put `command`
