### ISSUE TITLE
Can we have shelvery wrapped as Cfhighlander module

### ISSUE THREAD

**Issue by toshke** [base2Services/shelvery-aws-backups#113]
It would be nice to have following is method of deployment 
```shell
cfpublish github:base2services/shelvery-aws-backups
####
# click on the link to create the stack
####
```
cc @Guslington thoughts?

**Comment by Guslington** [comment]
@toshke interesting. So when you run cfpublish github:.... It clones the repo, builds the lambdas, compiles the cfhl components and publishes to S3? Or by deployment are you talking about handling the cloudformation create/update process as well?

**Comment by toshke** [comment]
Talking only about publishing the templates. Highlander anyway displays the
url to create or update the stack, though we could integrate this
functionality into kurgan
