### ISSUE TITLE
How to limit AMI creation to 1 EC2 with aws cli?

### ISSUE THREAD

**Issue by Rendanic** [base2Services/shelvery-aws-backups#116]
I want to create an AMI from only 1 EC2 with manual lambda execution:

`aws lambda invoke --function-name ShelveryBackups --payload '{"backup_type":"ec2ami","action":"create_backups","shelvery_select_entity":"i-0cd48a32e4def53ff"}' response.json`

The limitiation with `shelvery_select_entity` is not working.
Is it possible and what parameter is needed?

Regards
Thorsten

**Comment by toshke** [comment]
@Rendanic  `shelvery_select_entity` seems to be implmented according to https://github.com/base2Services/shelvery-aws-backups/blob/develop/shelvery/engine.py#L177 and https://github.com/base2Services/shelvery-aws-backups/blob/27429d2130e2a4000244c74a504d09cd95d98d0c/shelvery/runtime_config.py#L256  - can you try adding some debug statements on those lines and verify the value is not present

**Comment by Rendanic** [comment]
I checked it in command line mode. It is working but not in Lambda.
I try to add some debug code in Lamba...

**Comment by Rendanic** [comment]
I found the solution:

` aws lambda invoke --function-name ShelveryBackups --payload '{"backup_type":"ec2ami","action":"create_backups","config":{"shelvery_select_entity":"i-0cd48a32e4def53ff"}}' response.json`

Could we add this example to the documentation?
Environment variables are passed with a config block in JSON:
`"config":{"shelvery_select_entity":"i-0cd48a32e4def53ff"}`

**Comment by Rendanic** [comment]
I am closing the issue, due to existing example in chapter 'Configuration Priority 2: Lambda Function payload'. It is not exactly the same but good enough to understand the concept.
