### ISSUE TITLE
Problem with clean_backups and long retention time

### ISSUE THREAD

**Issue by Rendanic** [base2Services/shelvery-aws-backups#120]
`shelvery_custom_retention_types='AtlassianDaily:3456000‬'`

```
[ERROR]	2020-06-29T08:23:00.99Z	28b226b4-9bba-4074-a789-0eef48bcb393	Error checking backup hiddeninstancename-576b5f-2020-06-27-0100-daily for cleanup: invalid literal for int() with base 10: '3456000\u202c'
Traceback (most recent call last):
  File "/var/task/shelvery/engine.py", line 290, in clean_backups
    if backup.is_stale(self, RuntimeConfig.get_custom_retention_types(self)):
  File "/var/task/shelvery/runtime_config.py", line 156, in get_custom_retention_types
    rval[parts[0]] = int(parts[1])
ValueError: invalid literal for int() with base 10: '3456000\u202c'
```
The output is from CloudWatch

It is working with 10800 seconds:
`shelvery_custom_retention_types='AtlassianDaily:10800‬'
`

Any ideas what is going wrong here?

**Comment by Guslington** [comment]
@Rendanic could there be a weird character between `3456000‬` and the `'` ? https://www.fileformat.info/info/unicode/char/202c/index.htm

```
invalid literal for int() with base 10: '3456000\u202c'
```

it's is unable to convert to an int because of `\u202c` in the string
i was able to replicate the issue by copying the string from the issue into a python shell

```python
Python 3.7.6 (default, Dec 30 2019, 19:38:26)
>>> 'AtlassianDaily:3456000‬'.split(':')
['AtlassianDaily', '3456000\u202c']
>>> int('3456000\u202c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '3456000\u202c'
```

**Comment by Rendanic** [comment]
Thanks for the test. It was a really strange copy&paste failure in my setup who was not visible...
It has been fixed and everthing is fine.

Sorry for my failure.

Regards
Thorsten
