### ISSUE TITLE
Backups should be named by resource ID instead of the Name tag

### ISSUE THREAD

**Issue by rererecursive** [base2Services/shelvery-aws-backups#36]
Currently, the code for creating backup names is:
`name = entity_resource.tags['Name'] if 'Name' in entity_resource.tags else entity_resource.resource_id`
If two resources share the same value for the `Name` tag, then a backup will fail to create due to a naming conflict.
This logic should be reversed: the ID should be prioritised. 
I'm not sure if this will affect existing backups.

**Comment by toshke** [comment]
This has been implemented in release 0.5.0
